
Steps to record:
    1. Upload code
    2. Press Boot button (mode should change to 1 = true)
    3. Let Data Record. 
    4. Press Boot button (mode should change to 0 = false)
    5. Take out microSD card and use reader to download csv files

CSV files available: (header + values in csv files)
    imu_ICM45686
        returns:
            time,gyro x,gyro y,gyro z,accel x,accel y,accel z

    4x_tof_L7
        Instead of Zone X (ToF Name) as Header, it is D0, ..., D159 respectively. 
        e.g. D0-D63 = S1, D64-D127 (S2), D128-D143 (R), D144-D159 (F)
        returns: 
            time, Zone 0 (S1), .... , Zone 63 (S1), Zone 0 (S2), .... ,        Zone 63 (S2), Zone 0 (R), .... , Zone 15 (R), Zone 0 (F), .... ,        Zone 15 (F)
    Note: look at datasheet to identify were each zone is (they are at different angles)
        Link: https://www.st.com/resource/en/datasheet/vl53l7cx.pdf

    of_PMW3901
        returns:
            time,deltaX,deltaY
