
Steps to record:
    1. Upload code
    2. Press Boot button (mode should change to 1 = true)
    3. Let Data Record. 
    4. Press Boot button (mode should change to 0 = false)
    5. Take out microSD card and use reader to download csv files

CSV files available: (header + values in csv files)
    imu_ICM45686
        returns:
            time,gyro x,gyro y,gyro z,accel x,accel y,accel z

    4x_tof_L7
        The type is: S1, S2, R, F
        Type refers to the specific ToF being called upon. 
        S1 and S2 are D0 to D63; R and F are from D0 to D15
        returns:
            time,type,D0,...,D63

    Note: look at datasheet to identify were each zone is (they are at different angles)
        Link: https://www.st.com/resource/en/datasheet/vl53l7cx.pdf

    of_PMW3901
        returns:
            time,deltaX,deltaY


Bug:
    When data is not ready from one of the Tofs, then it skips it and returns the next set of ToF data;
    therefore tof data will be misalgined
    fix code to return Xs if not reday. 